# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - doaibustore

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: npm install, build, and test
        env:
          DATABASE_URL: "sqlserver://build:temp@localhost:1433;database=temp;user=temp;password=temp;encrypt=true;"
          JWT_SECRET: "build-time-secret"
          NEXTAUTH_SECRET: "build-time-nextauth-secret"
          NEXTAUTH_URL: "https://doaibustore.site"
          NODE_ENV: "production"
        run: |
          npm ci
          npm run build
          
          # Verify build output
          ls -la .next || echo ".next folder not created"
          
          # List build output
          echo "Build completed. Checking output:"
          ls -la

      - name: Zip artifact for deployment
        run: |
          # Remove node_modules to avoid size issues
          rm -rf node_modules
          
          # Create zip with essential files only
          zip -r release.zip . -x "*.git*" "node_modules/*" ".env*" "*.log" "coverage/*" ".nyc_output/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_98343B524EC149B09B2BAF053632C6F9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8A72675D09B4437A8B79B90A75DD6CC0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9901E9BE8782443796A7EE83CA8D5454 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'doaibustore'
          slot-name: 'Production'
          package: release.zip
          